### ISSUE TITLE
sdk clean up

### ISSUE THREAD

**Issue by joshuabell** [uport-project/uport-ios-sdk#2]
- remove server references we are deprecating
- figure out what else has to change and make adjustments
- integrate with UPTEthereumSigner

**Comment by popaaaandrei** [comment]
Guys, is there any reason why there are a lot of NSObject subclasses used?

**Comment by joshuabell** [comment]
Hey @popaaaandrei  thanks for the question! I love the features NSObject and the NSObjectProtocol provide and I reflexively use NSObject as a root class for my classes in Swift for Obj-C compatibility and API consistency. Additionally, when NSObject is not the root class introspection matters could become more complex, debugging could become more difficult and polymorphism may be unavailable. I can't think of a better root class for my class hierarchies and I'm concerned about the dangers of not subclassing an object.

Using NSObject as a root class is standard in Objective-C since iOS 2.0 and most class hierarchies Apple provides in Objective-C (e.g. UIViewController, UIView, NSNotificationCenter, NSArray, NSNumber) use NSObject for a root class. Given how fundamental NSObject is to iOS development, I am surprised Apple allows no base class for custom objects in Swift as an option. I'm not convinced that's a good language design choice, yet. 

I'm happy to hear any counterproposals on what the root class should be instead or counterarguments on why there should be no root class.

**Comment by popaaaandrei** [comment]
@joshuabell thank you for your response!
I could try to describe some reasons. And please excuse the bias.

- NSObject is only used in UIKit world, in Foundation (almost) everything is a struct. And that's because UIKit was written (entirely in Objective-C) when Swift was not available. Apple is committed to move away from Objective-C and to rewrite everything in Swift at some point.
- OOP was hot 20 years ago when the alternative was pure C and "multi-core" was only available in high-performance computing architectures; now we are moving to functional programming and parallel programming. Most of the work in advancing programming languages for the last 20 years was mostly about not doing OOP anymore (like eliminating shared mutable state).
- Most new iPhones have quad/six-cores.
- Using structs _without inheriting from NSObject_ provides a lot of benefits like performance, immutability, copy-on-write, multi-threading, etc. It's the basis for any decent concurrency paradigm. You can also check [Chris Lattner's concurrency manifesto](https://gist.github.com/lattner/31ed37682ef1576b16bca1432ea9f782) for more expert arguments.
- A lot of people (including myself) use RxSwift/ReactiveCocoa a lot. And this doesn't work very well with reference types (the whole paradigm of functional programming implies immutability and separation).
- And this leads me to the problems that `Realm` has in iOS especially because they enforce that every model inherits from `Object`. Their documentation even says `The only thing you have to be aware of is that you cannot have multiple threads sharing the same instances of Realm objects. ` And this of course leads to a lot of crashes that are very hard to replicate. Most of the solutions resolve in reading data from Realm and mapping them to structs, specifically because they are not reference types.
-  I might be wrong/biased here, but Swift is about migrating away from Objective-C constructs to protocol composition, immutability and memory separation. That would also allow us to separate what is purely iOS with layers that could also run (later) on Server-side Swift. A lot of people are starting to use Swift for systems programming specifically because it's a very performant (and compiled) language.

Thank you for your time and for doing this,
Andrei

**Comment by joshuabell** [comment]
@popaaaandrei great points! love it. I'm a big fan of RxSwift/ReactiveCocoa as well. Haven't had a chance to use Realm myself, been to their offices for meetups and am familiar with Realm's value prop. I understand your pain points with Realm and have experienced similar issues in different situations.

I've considered your input and decided it's better from a Swift design/asthetic point of view to move away from subclassing NSObject. I'll favor structs not classes too.

It will be a beautiful day when Apple has completely Swiftified UIKit, no remnants of Objective-C remain and functional programming is standard. Many moons will pass before that day comes though. However, I think it's important to use any language's current design principles including ones that will be adopted in the future. Thank you for bringing to my attention that I was veering from that direction.

**Comment by popaaaandrei** [comment]
@joshuabell Thank you for your kind words! Please tell me if I can help you guys with anything.
